# ansible_port: 7722

listen_port: 8088

backup_path: /tmp/bckup1

var0: true
var1: "Yes"

ansible_root: /tmp/ansible-playbook
# project_name: ansible_playbook_creator

project_name: nfs

users:
  - mehrdad
  - hamid
  - leila

dict:
  Env: production
  App: my-app
  Ver: v1.7

user_prompt: no

